apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: wordpress
  namespace: wordpress
spec:
  network:
    # Expose rules generate Istio VirtualServices and related network policies
    expose:
      - service: wordpress
        selector:
          app.kubernetes.io/name: wordpress
        gateway: tenant
        host: wordpress
        port: 8080
  # SSO allows for the creation of Keycloak clients and with automatic secret generation and protocolMappers
  sso:
    - name: wordpress SSO
      clientId: uds-core-wordpress
      redirectUris:
        - "https://wordpress.uds.dev/wp-admin"
      enableAuthserviceSelector:
        app.kubernetes.io/name: wordpress
      groups:
        anyOf:
          - "/UDS Core/Admin"