apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: wordpress
  namespace: wordpress
spec:
  network:
    # Expose rules generate Istio VirtualServices and related network policies
    expose:
      - service: wordpress
        selector:
          app.kubernetes.io/name: wordpress
        gateway: tenant
        host: wordpress
        port: 8080
  # SSO allows for the creation of Keycloak clients and with automatic secret generation and protocolMappers
  sso:
    - name: Podinfo SSO
      clientId: uds-core-podinfo
      redirectUris:
        - "https://wordpress.uds.dev/wp-admin"
      enableAuthserviceSelector:
        app.kubernetes.io/name: wordpress
      groups:
        anyOf:
          - "/UDS Core/Admin"
  monitor:
    - selector:
        app.kubernetes.io/name: wordpress
      targetPort: 8080
      portName: http
      description: "podmonitor"
      kind: PodMonitor
    - selector:
        app.kubernetes.io/name: podinfo
      targetPort: 9898
      portName: http
      description: "svcmonitor"
      kind: ServiceMonitor






apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: wordpress
  namespace: wordpress
spec:
  network:
    # Expose rules generate Istio VirtualServices and related network policies
    expose:
      - service: wordpress
        selector:
          app.kubernetes.io/name: wordpress
        gateway: tenant
        host: wordpress
        port: 9898